name: wallet
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  calendar_view: ^1.1.0
  equatable: ^2.0.5
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^25.2.4
  timezone: ^0.9.3
  uuid: ^4.3.3

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
