// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2fHDL9t9pF0EZN2lp4I6qrOperKOfMAE',
    appId: '1:794238169340:web:8cf0432f3a0af9a3526779',
    messagingSenderId: '794238169340',
    projectId: 'wallet-gapjyk',
    authDomain: 'wallet-gapjyk.firebaseapp.com',
    storageBucket: 'wallet-gapjyk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu13k_kvUwHj2fkvyx9aynsUIJFABtQlA',
    appId: '1:794238169340:android:1c022d2ee89d7821526779',
    messagingSenderId: '794238169340',
    projectId: 'wallet-gapjyk',
    storageBucket: 'wallet-gapjyk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn7oheGxjGQoNzmgKnDb_4Y9eLeba7Gqs',
    appId: '1:794238169340:ios:6d8ff65a24f1877a526779',
    messagingSenderId: '794238169340',
    projectId: 'wallet-gapjyk',
    storageBucket: 'wallet-gapjyk.firebasestorage.app',
    iosBundleId: 'dev.merdan.wallet.WalletWidget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn7oheGxjGQoNzmgKnDb_4Y9eLeba7Gqs',
    appId: '1:794238169340:ios:0c59718b0b848005526779',
    messagingSenderId: '794238169340',
    projectId: 'wallet-gapjyk',
    storageBucket: 'wallet-gapjyk.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2fHDL9t9pF0EZN2lp4I6qrOperKOfMAE',
    appId: '1:794238169340:web:15deb9e36d54344d526779',
    messagingSenderId: '794238169340',
    projectId: 'wallet-gapjyk',
    authDomain: 'wallet-gapjyk.firebaseapp.com',
    storageBucket: 'wallet-gapjyk.firebasestorage.app',
  );

}