class DefaultItem {
  static List<Map<String, dynamic>> accounts = [
    {
      'id': 1,
      'name': 'Cash',
      'image': 'assets/images/money.png',
      'desc': 'Account for cash money accounting',
    },
    {
      'id': 2,
      'name': 'Card',
      'image': 'assets/images/credit-caard.png',
      'desc': 'It\'s for Bank accounts, credit card and etc.',
    },
  ];
  static List<Map<String, dynamic>> categories = [
    {
      'id': 1,
      'name': 'Car',
      'image': 'assets/images/car.png',
      'desc': 'Expenses for personal car',
      'type': -1,
    },
    {
      'id': 2,
      'name': 'Drinks',
      'image': 'assets/images/drinks.png',
      'desc': 'Expenses for bars and drinks',
      'type': -1,
    },
    {
      'id': 3,
      'name': 'Food',
      'image': 'assets/images/food.png',
      'desc': 'Expenses for eating out and buying food',
      'type': -1,
    },
    {
      'id': 4,
      'name': 'Gift',
      'image': 'assets/images/gift.png',
      'desc': 'Expenses for buying gifts and other stuff',
      'type': -1,
    },
    {
      'id': 5,
      'name': 'Groceries',
      'image': 'assets/images/groceries.png',
      'desc': 'Expenses for groceries and other stuff',
      'type': -1,
    },
    {
      'id': 6,
      'name': 'Home',
      'image': 'assets/images/home.png',
      'desc': 'Expenses for home spending',
      'type': -1,
    },
    {
      'id': 7,
      'name': 'Internet',
      'image': 'assets/images/internet.png',
      'desc': 'Expenses for internet and phone',
      'type': -1,
    },
    {
      'id': 8,
      'name': 'Health care',
      'image': 'assets/images/health-care.png',
      'desc': 'Expenses for medicine and hospital',
      'type': -1,
    },
    {
      'id': 9,
      'name': 'Pets',
      'image': 'assets/images/pets.png',
      'desc': 'Expenses for home pets',
      'type': -1,
    },
    {
      'id': 10,
      'name': 'Clother',
      'image': 'assets/images/shirt.png',
      'desc': 'Expenses for clothers',
      'type': -1,
    },
    {
      'id': 11,
      'name': 'Sport',
      'image': 'assets/images/sport.png',
      'desc': 'Expenses for sport and etc.',
      'type': -1,
    },
    {
      'id': 12,
      'name': 'Taxi',
      'image': 'assets/images/taxi.png',
      'desc': 'Expenses for taxi',
      'type': -1,
    },
    {
      'id': 13,
      'name': 'Toiletries',
      'image': 'assets/images/toiletries.png',
      'desc': 'Expenses for toiletries',
      'type': -1,
    },
    {
      'id': 14,
      'name': 'Public transport',
      'image': 'assets/images/transport.png',
      'desc': 'Expenses for public transport',
      'type': -1,
    },
    {
      'id': 15,
      'name': 'Currency exchange',
      'image': 'assets/images/currency-exchange.png',
      'desc': 'Incomes from currency exchange and stock profit',
      'type': 1,
    },
    {
      'id': 16,
      'name': 'Salary',
      'image': 'assets/images/income.png',
      'desc': 'Incomes from salary and side profit',
      'type': 1,
    },
    {
      'id': 17,
      'name': 'Savings',
      'image': 'assets/images/savings.png',
      'desc': 'Savings from bank account',
      'type': 1,
    },
  ];
}
